language: node_js
node_js:
    - "4.8"
    - "5.12"
    - "6.10"
    - "7.10"

addons:
  codeclimate:
    repo_token:
      - secure: CODECLIMATE_REPO_TOKEN

install:
    - npm install
    - npm install -g codecov
    - npm install -g codacy-coverage
script:
    - npm test
    - npm run coverage
after_success:
    - codecov
    - npm install -g codeclimate-test-reporter
    - codeclimate-test-reporter < coverage/lcov.info
    - codacy-coverage < coverage/lcov.info
